FROM node:20-alpine

WORKDIR /usr/src/app

# Install pnpm globally
RUN npm install -g pnpm

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json  ./package.json
COPY ./turbo.json  ./turbo.json

COPY ./apps/web ./apps/web


# Install dependencies
RUN pnpm install
RUN pnpm run db:generate
RUN DATABASE_URL= ${DATABASE_URL} pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]
